;=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
; Init
;=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
; Generated by CBM prg Studio

; 10 SYS2112

*=$0801

        BYTE    $0B, $08, $0A, $00, $9E, $32, $31, $31, $32
        BYTE    $3A, $A2, $00, $00, $00

*=$0840
        ldx #$00
loop
        lda $0900,x
        sta $c000,x
        lda $0a00,x
        sta $c100,x
        inx
        bne loop
        jsr $c000
        rts
*=$0900
        INCBIN "addcommand.prg",2