;=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
; Load and Display Koala PIC format in C64 Assembler
;=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
; Generated by CBM prg Studio

; 10 SYS (2304):REM emarti

*=$0801

        BYTE $17, $08, $0A, $00, $9E, $20, $28, $32
        BYTE $33, $30, $34, $29, $3a, $8f, $20, $45
        BYTE $4D, $41, $52, $54, $49, $00, $00, $00

; koala pic viewer for C64
; (c) 2019 Jan
; Coded by emarti, Murat Özdemir

*=$0900        

VIDEO      = $3F40
COLOR      = $4328
BACKGROUND = $4710

        JSR $E544       ; CLEAR SCREEN

        LDA #$00
        STA $D020       ; BORDERCOLOUR

        LDA BACKGROUND        
        STA $D021       ; BACKGROUNDCOLOUR

        LDA #$3B        ; bitmap mode on
        STA $D011

        LDA #$18        
        STA $D018       ; set bitmap address($2000) and screen($0400) 
        STA $D016       ; multi color on

        LDA #$03        ; set vic bank
        STA $DD00
        
        LDA #$40        ; set video ram
        STA $FB
        LDA #$3F
        STA $FC
        LDA #$04
        STA $FE
        LDA #$08
        STA VALBYTE
        JSR SET
        
        LDA #$28        ; set color ram
        STA $FB
        LDA #$43
        STA $FC
        LDA #$D8
        STA $FE
        LDA #$DC
        STA VALBYTE
        JSR SET

        JMP *

        ; function move bytes
VALBYTE  BYTE $00

SET     LDY #$00
L1      LDA ($FB),Y
        STA ($FD),Y
        INY
        BNE L1
        INC $FC
        INC $FE
        LDX $FE
        CPX VALBYTE
        BNE L1
        RTS

*=$2000
        ; koala picture data
        INCBIN "car.bin",2

      