;=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
; No border
;=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
; Generated by CBM prg Studio

; 10 SYS (2080)

*=$0801

        BYTE    $0E, $08, $0A, $00, $9E, $20, $28,  $32, $30, $38, $30, $29, $00, $00, $00
*=$0820
        
        sei

        lda #$7f
        sta $dc0d    
        sta $dd0d
        and $d011    
        sta $d011

        lda #<borderoff
        sta $0314
        lda #>borderoff
        sta $0315

        lda #$01                
        sta $d01a

        ; clear border garbage
        lda #00
        sta $3fff

        cli
        jmp *


borderoff       
        lsr $d019

        lda $d011     ; switch to 24 row mode
        and #247
        sta $d011

        lda #252
        sta $d012
        lda #<normal
        sta $0314
        lda #>normal
        sta $0315
        jmp $ea81


normal       
        lsr $d019
        lda $d011     ; restore 25 row mode
        ora #08
        sta $d011
        lda #249
        sta $d012
        lda #<borderoff
        sta $0314
        lda #>borderoff
        sta $0315
        jmp $ea81

