;=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
; SID's Random Number Generator
;=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
; Generated by CBM prg Studio
; 10 SYS (2064)

*=$0801

        BYTE    $0E, $08, $0A, $00, $9E, $20, $28,  $32, $30, $36, $34, $29, $00, $00, $00

*=$0810

        jsr setrnd
        ldx #$00
loop    
        lda $d41b       ; get random value $00-$ff
        cmp #$30        ; $30 < randomvalue < $3a ( 0-9 characters)
        bcc loop
        cmp #$3a
        bcs loop
        sta $0400,x     ; write random value
        inx
        cpx #$28
        bne loop
        rts

setrnd     
        lda #$ff        ; max. freq. value
        sta $d40e       ; voice 3 freq. low byte
        sta $d40f       ; voice 3 freq. high byte
        lda #$80        ; noise waveform, gate bit off
        sta $d412       ; voice 3 control register
        rts