;=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
; Illegal Opcodes
;=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
; Generated by CBM prg Studio
; Check "Use unpublished opcodes" from Tools/Options/Assembler

; 10 SYS (2080)


*=$0801

        BYTE    $0E, $08, $0A, $00, $9E, $20, $28, $32
        BYTE    $30, $38, $30, $29, $00, $00, $00

*=$0820

        ; SLO (ASO) {addr} = {addr} * 2, a = a or {addr}
        ; asl {addr}
        ; ora {addr}

        lda #$f0

        ; asl value
        ; ora value
        ;----------or
        aso value
        
        sta result
        rts

*=$0900

value   byte $0f
result  byte $00
