;=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
; Illegal Opcodes
;=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
; Generated by CBM prg Studio
; Check "Use unpublished opcodes" from Tools/Options/Assembler

; 10 SYS (2080)


*=$0801

        BYTE    $0E, $08, $0A, $00, $9E, $20, $28, $32
        BYTE    $30, $38, $30, $29, $00, $00, $00

*=$0820

        ; LAX   a,x = {addr}
        ;====================
        ; lda $0286
        ; tax
        ;----- or
        ; lda $0286
        ; ldx $0286
        ;----- or
        ; ldx $0286
        ; txa
        ;----- or
        lax $0286

        sta $d020
        stx $d021
        
        

        rts
