;=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
; Multi Hello
;=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=
; Generated by CBM prg Studio

; 10 SYS4096

*=$0801

        BYTE    $0B, $08, $0A, $00 
        BYTE    $9E, $34, $30, $39 
        BYTE    $36, $00, $00, $00

*=$1000
        
        ; set border and background color
        ldx #$00
        stx $d021
        dex
        stx $d020
        ; -------------------------------

        ; clear screen 1
        ;jsr $E544
        ; --------------

        ; clear screen 2
        ;lda #$93
        ;jsr $ffd2
        ; --------------

        ; clear screen 3
        ldy #$00
        lda #$20
        sta $0400,y
        sta $0500,y
        sta $0600,y
        sta $0700,y
        iny
        bne *-13
        ; --------------

        ; write 1
        ldx #$00
        lda MESAJ,x
        sta $0400,x
        inx
        cpx #$0b
        bne *-9
        ; -------

        ; set cursor color for white
        lda #$01
        sta $0286
        ; ----------------

        ; set cursor for row and column
        ldx #$05
        ldy #$15
        jsr $e50c
        ; -----------------------------

        ; write 2
        lda #<MESAJ2
        ldy #>MESAJ2
        jsr $ab1e
        ; -------

        ; write 3
        ldx #$00
        lda MESAJ2-3,x
        jsr $ffd2
        inx
        cpx #$0e
        bne *-9
        ; -------

        ; press any key to continue
        jsr $ffe4
        beq *-3
        ; -------------------------

        ; return BASIC
        rts


MESAJ   TEXT 'hello world'
        BYTE $0d, $0d, $0d        ; return x 3
MESAJ2  TEXT "hello world"
        BYTE $00

